BEGIN TRANSACTION;

/* Create a table called NAMES */
CREATE TABLE GIAOVIEN(Id integer PRIMARY KEY, TenGV text);
CREATE TABLE DETAI(Id integer, TenDT text);
CREATE TABLE CONGVIEC(MaDT integer, SoTT integer, TenCV text);
CREATE TABLE THAMGIA(MaGV integer, MaDT integer, SoTT integer);

/* Create few records in this table */
INSERT INTO GIAOVIEN VALUES(1,'Tom');
INSERT INTO GIAOVIEN VALUES(2,'Lucy');
INSERT INTO GIAOVIEN VALUES(3,'Frank');
INSERT INTO GIAOVIEN VALUES(4,'Jack');
INSERT INTO GIAOVIEN VALUES(5,'Jenny');

INSERT INTO DETAI VALUES(1,'FPT');
INSERT INTO DETAI VALUES(2,'TechBase');
INSERT INTO DETAI VALUES(3,'ITViec');

INSERT INTO CONGVIEC VALUES(1,1,'OT');

INSERT INTO CONGVIEC VALUES(2,1,'Funny');
INSERT INTO CONGVIEC VALUES(2,2,'Study');

INSERT INTO CONGVIEC VALUES(3,1,'Eat');
INSERT INTO CONGVIEC VALUES(3,2,'Sleep');
INSERT INTO CONGVIEC VALUES(3,3,'Code');

INSERT INTO THAMGIA VALUES(1,1,1);

INSERT INTO THAMGIA VALUES(2,2,1);
INSERT INTO THAMGIA VALUES(2,2,2);

INSERT INTO THAMGIA VALUES(3,2,2);

INSERT INTO THAMGIA VALUES(4,1,1);
INSERT INTO THAMGIA VALUES(4,2,1);
INSERT INTO THAMGIA VALUES(4,2,2);
INSERT INTO THAMGIA VALUES(4,3,1);
INSERT INTO THAMGIA VALUES(4,3,2);
INSERT INTO THAMGIA VALUES(4,3,3);

COMMIT;

SELECT *
FROM GIAOVIEN GV
WHERE NOT EXISTS (SELECT *
                  FROM THAMGIA TG
                  WHERE TG.MaGV = GV.Id)
(5,'Frank')

SELECT *
FROM GIAOVIEN G
WHERE NOT EXISTS (SELECT *
                 FROM CONGVIEC C
                 WHERE NOT EXISTS (SELECT *
                                   FROM THAMGIA TG
                                   WHERE C.Id = TG.MaCV AND G.Id = TG.MaGV))
(1,'Tom')
(4,'Frank')

SELECT *
FROM GIAOVIEN G
WHERE EXISTS (SELECT *
                 FROM CONGVIEC C
                 WHERE NOT EXISTS (SELECT *
                                   FROM THAMGIA TG
                                   WHERE C.Id = TG.MaCV AND G.Id = TG.MaGV))
(2,'Lucy')
(3,'Frank')
(5,'Frank')


SELECT *
FROM GIAOVIEN G
WHERE NOT EXISTS (SELECT *
                 FROM CONGVIEC C, DETAI D
                 WHERE D.Id = C.MaDT AND NOT EXISTS (SELECT *
                                   FROM THAMGIA TG
                                   WHERE C.MaDT = TG.MaDT AND TG.SoTT = C.SoTT AND G.Id = TG.MaGV
                                  )
                 )

SELECT TG.MaGV, TG.MaDT, COUNT(*)
FROM GIAOVIEN G, CONGVIEC CV, THAMGIA TG
WHERE G.Id = TG.MaGV AND TG.MaDT = CV.MaDT AND TG.SoTT = CV.SoTT
GROUP BY TG.MaGV, TG.MaDT


SELECT DISTINCT TG.MaGV
FROM GIAOVIEN G, CONGVIEC CV, THAMGIA TG
WHERE G.Id = TG.MaGV AND TG.MaDT = CV.MaDT AND TG.SoTT = CV.SoTT
GROUP BY TG.MaGV, TG.MaDT
HAVING COUNT(*) = ANY (SELECT COUNT(*)
                       FROM DETAI D, CONGVIEC C
                       WHERE D.Id = C.MaDT AND TG.MaDT = D.Id
                       GROUP BY D.Id)


